### ISSUE TITLE
LCFIT doesn't start

### ISSUE THREAD

**Issue by bastiencarreres** [dessn/Pippin#162]
Hi, I try to fit some simulations on Permulter the fit section of my Pippin file (`$SNANA_LSST_USER/bastienc/LSST_SNANA/LSST_Uchuu_BC.yml`) is:

```
LCFIT:
  LSST_FIT:
    # MASK means only apply this light curve fitting on sims/Dataprep which have DES in the name
    # You can also specify a list for this, and they will be applied as a logical or
    MASK: LSST_RNDSMEAR
    # The base nml file used 
    BASE: /global/cfs/cdirs/lsst/groups/TD/SN/SNANA/SURVEYS/LSST/USERS/bastienc/LSST_SNANA/fit_inputs/LSST_fit.nml
    OPTS:
      BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_DEFAULT.TEMPLATE 20
```
Pippin return the error:

```
[  NOTICE |           manager.py:453]   FINISHED: SNANASimulation LSST_BS20 task (wall time 1:24:03, 20 jobs, deps []) with 20 NUM_JOBS. NUM_JOBS now 0
[    INFO |           manager.py:368]   
[  NOTICE |           manager.py:370]   LAUNCHING: SNANALightCurveFit LSST_FIT_LSST_RNDSMEAR task (20 jobs, deps ['LSST_RNDSMEAR'])
[   DEBUG |              task.py:132]   Set cpu header
[   DEBUG |              task.py:136]   Set gpu header
[   ERROR |           manager.py:379]   'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/global/cfs/cdirs/desc-td/SOFTWARE/Pippin/pippin/manager.py", line 377, in execute
    started = t.run()
  File "/global/cfs/cdirs/desc-td/SOFTWARE/Pippin/pippin/task.py", line 307, in run
    return self._run()
  File "/global/cfs/cdirs/desc-td/SOFTWARE/Pippin/pippin/snana_fit.py", line 301, in _run
    regenerate, new_hash = self.write_nml()
  File "/global/cfs/cdirs/desc-td/SOFTWARE/Pippin/pippin/snana_fit.py", line 262, in write_nml
    self.yaml["CONFIG"][key] = value
TypeError: 'NoneType' object is not subscriptable
```
the bug don't seems to be only on permulter, I got the same on midway...

**Comment by OmegaLambda1998** [comment]
So I believe the issue is your nml file (/project2/rkessler/SURVEYS/LSST/USERS/bcarreres/fit_inputs/LSST_fit.nml) does not include a YAML section.

It should be as simple as adding:
```
CONFIG:
    BATCH_INFO: sbatch $SBATCH_TEMPLATES/SBATCH_Midway2b.TEMPLATE 20
    VERSION:
    OUTDIR:

#END_YAML
```

Just replace BATCH_INFO with your prefered template. If that does work, please let me know!

**Comment by bastiencarreres** [comment]
It solved the problem! Thank you!
